### ISSUE TITLE
Remove/Rename Test Results — spec_index.ts.png

### ISSUE THREAD

**Issue by deneshr** [jf3096/json-typescript-mapper#13]
@jf3096 
The image file under git-img, named **Test Results — spec_index.ts.png** is interfering with a NativeScript android project build.
The android build process seems to crash due to the file name. 
The error goes as... `json-typescript-mapper\git-img\Test Results ù spec_index.ts.png: error: Invalid filename.  Unable to add.`
I had to rename the file and _remove the long dash character_ to get the build process to go smooth.
Would it be possible for you to rename this particular file to play nice with the android build process?
Thanks.

**Comment by jf3096** [comment]
The image was generated by webstorm. I have renamed it manually.

**Comment by jf3096** [comment]
The image is generated by webstorm. I have renamed it manually.

**Comment by deneshr** [comment]
This works. Thanks.
