### ISSUE TITLE
How to use in a project with target ES6

### ISSUE THREAD

**Issue by andrashatvani** [jf3096/json-typescript-mapper#5]
After including the library in the project the following error message will be shown:

`json-typescript-mapper:1
import 'reflect-metadata';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
`

Target:ES6 is a must due to async-await as the migration to TS 2.1 haven't been done yet.

**Comment by jf3096** [comment]
I cannot fully understand your question, the library by default support @ which is decorator. So it should support either es5 or es6
